# Generated by Django 4.1.1 on 2022-09-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brands',
        ),
        migrations.RenameModel(
            old_name='SubCatagories',
            new_name='SubCategories',
        ),
    ]
