# Generated by Django 4.1.1 on 2022-09-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-home', max_length=50),
        ),
    ]
