# Generated by Django 4.1.1 on 2022-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
