# Generated by Django 4.1.1 on 2022-09-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_brand_alter_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='pname',
        ),
    ]
