# Generated by Django 4.1.1 on 2022-09-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_p_name_product_pname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=400)),
                ('profession', models.CharField(max_length=600)),
                ('profile_pic', models.ImageField(upload_to='media')),
                ('rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=2)),
                ('feed_back', models.TextField()),
            ],
        ),
    ]
