# Generated by Django 4.1.1 on 2022-09-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_feedbacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBacks',
            new_name='FeedBack',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_back',
            new_name='description',
        ),
    ]
