# Generated by Django 4.1.1 on 2022-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
