# Generated by Django 4.1.1 on 2022-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.CharField(blank=True, max_length=90, unique=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.CharField(blank=True, max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
